

set(CMAKE_SYSTEM Windows)
set(CMAKE_SYSTEM_PROCESSOR i686)
set(MINGW_TOOLS "/usr/i686-w64-mingw32")
set(CMAKE_C_COMPILER "/usr/bin/i686-w64-mingw32-gcc")
set(CMAKE_C_LINK_EXECUTABLE "${MINGW_TOOLS}/bin/ld")

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -m32")
set(CMAKE_LINKER_FLAGS "${CMAKE_LINKER_FLAGS} -m32")

set(CMAKE_SYSROOT "/usr/i686-w64-mingw32/sys-root")
set(CMAKE_FIND_ROOT_PATH "/usr/i686-w64-mingw32")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
